# Generated by Django 6.0.3 on 2026-03-21 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя исполнителя')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Страна исполнителя')),
                ('start_year', models.IntegerField(blank=True, null=True, verbose_name='Начало карьеры')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='musician_covers/', verbose_name='Фото исполнителя')),
                ('description', models.TextField(blank=True, verbose_name='Об исполнителе')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название альбома')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата выхода')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='album_covers/', verbose_name='Обложка альбома')),
                ('genre', models.CharField(blank=True, choices=[('rock', 'Рок'), ('pop', 'Поп'), ('hip_hop', 'Хип-хоп'), ('jazz', 'Джаз'), ('classical', 'Классическая'), ('electronic', 'Электронная'), ('rnb', 'R&B'), ('folk', 'Фолк'), ('other', 'Другое'), ('metal', 'Метал'), ('blues', 'Блюз')], default='other', max_length=50, null=True, verbose_name='Жанр')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Albums', to='music.musician', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='MusicTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название трека')),
                ('file', models.FileField(blank=True, null=True, upload_to='mus_files/', verbose_name='файл трека')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='дата выхода')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='track_covers/', verbose_name='Обложка трека')),
                ('is_folove', models.BooleanField(default=False, verbose_name='В избранном')),
                ('genre', models.CharField(blank=True, choices=[('rock', 'Рок'), ('pop', 'Поп'), ('hip_hop', 'Хип-хоп'), ('jazz', 'Джаз'), ('classical', 'Классическая'), ('electronic', 'Электронная'), ('rnb', 'R&B'), ('folk', 'Фолк'), ('other', 'Другое'), ('metal', 'Метал'), ('blues', 'Блюз')], default='other', max_length=50, null=True, verbose_name='Жанр')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album', verbose_name='Альбом')),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.musician', verbose_name='Исполнитель')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
    ]
