FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app

RUN echo "Django==4.2.16" > requirements.txt && \
    echo "gunicorn==21.2.0" >> requirements.txt && \
    echo "Pillow==10.1.0" >> requirements.txt && \
    echo "whitenoise==6.6.0" >> requirements.txt


RUN pip install --default-timeout=200 --no-cache-dir -r requirements.txt

COPY / .

RUN mkdir -p staticfiles